ReadingsArrays.PraxisArrayFR= [[
    [
    Prefix.praxis+"&D=0210||011stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:13:25-33", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=012ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:19-26", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=014thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:36-42", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=015thSunday||062ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:9-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0201&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:12:1-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0801||2304&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:21-29", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1601&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:31-43", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1701||Pntl2&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:34-43", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1801&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:8-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1901&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:3:12-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2101&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:19:11-17", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2601&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:2-7", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=021stSunday||3004&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:13:36-43", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=022ndSunday||051stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:24-End/15:1-3", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=023rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:4-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=024thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:36-End/16:1-5", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1202&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:12-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1402&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:8:26-38", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2202||0109||041stSunday||Pntl39&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:1:1-14", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=031stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:37-End/11:1-1", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=032ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:19-29", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=033rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:30-42", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=034thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:16:40-End/17:1-7", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0803&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:2-14", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0903&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:15-24", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1203&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:1-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1503||1312&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:44-60/8:1-1", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1703||0311&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:20:17-38", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2403&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:6-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2503&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:12:25-End/13:1-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2703||0605&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:13-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2803&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:36-41/16:1-5", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2903&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:12:1-24", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=042ndSunday||2907&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:30-34", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=043rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:35-50", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2804&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:13:13-25", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2904&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:13:26-32", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0105&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:6:1-15/7:1-2", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0305&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:22-30", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=052ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:22-29", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=053rdSunday||JFast1&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:2:38-45", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=JFast2&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:17:30–34", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=JFast3&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:12-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=JFast4&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:3:22-26", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1005&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:16:25-34", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1105&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:24-End/19:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1205&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:8:26-39", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2205&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:19-26", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0206&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:12-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=061stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:3-9", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=063rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:20:7–16", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=064thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:8:5–13", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2308&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:16:16-34", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2708||1009&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:19:23-41", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=3008&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:36-End/16:1-5", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=094thSunday||102ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:8-22", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1307||101stSunday||093rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:12:25-End/13:1-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=103rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:17:1–12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=104thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:1–11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1610||0413||2009&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:24-End/19:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=3010||044thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:8-22", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=111stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:12-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=112ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:19-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=113rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:12-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=114thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:19:11-22", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2011&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:27:42-44/28:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0312&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:13-29", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=121stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:12-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=123rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:21:8-14", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=124thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:19-30", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Jonh3&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:12-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1712&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:12-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2512&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:24-End/19:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2812||2409&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:20-34", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2912&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:34-42", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=3012&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:30-37", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0113||0405||2609||0511&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:3:1-16", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0213&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:1-7", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0313||2204&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:21-33", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL10&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:36-End/5:1-11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL11||Pntl4&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:13-22", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL12&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:3-11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL13&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:12:12-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL14&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:22-31", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL15&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:22:17-30", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL17&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:17:10-14", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL18&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:27:9-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL19&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:28:7-11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL1&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:21:1-14", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL20&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:28:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL21||Pntl34&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:23:6-11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL22&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:23:12-35", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL24||054thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:2-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL25&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:27:1-3", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL26&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:26-End/12:1-2", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL27||Pntl6&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:19-31", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL29&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:24:24-End/25:1-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL2ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:21:40-End/22:1-16", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL1stSunday||GL2&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:21:15-26", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL31&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:25-35", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL32&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:24:10-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL33||0613&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:11:12-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=3005||GL34&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:21:5-14", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL35&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:36-End/16:1-3", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL36||GL43&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:26:1-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL38&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:18:9-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=2702||2203||2612||GL39&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:19:11-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL3&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:19-28", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL3rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:23:1-11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL40&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:26:1-8", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL41&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:27:16-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL42&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:8:9-17", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL45||013rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:22-31", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL46||GL28&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:22:17-21/22:22-24", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL47&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:19:23-26", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL48&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:25:23-End/26:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL49&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:1-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL4&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:34-42", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL4thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:24:1-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL50&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:27:38-End/28:1-10", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL5&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:9-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL5thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:25:13-End/26:1-1", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=1305||2605||GL6&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:8:3-13", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL6thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:26:19-End/27:1-8", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL7&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:2:42-End/3:1-9", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL7thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:27:27-37", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL8&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:21:27-39", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL8thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:28:11-31", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl10&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:8-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl11&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:13-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl12&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:19-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl13&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:31-35", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl15&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:23-27", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl16&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:27-31", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl17&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:32-35", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl18&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl19&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:5-11", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl1&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:3:1-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=0101||Pntl1stSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:17:16-34", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl20&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:12-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl22&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:21-25", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl23||Pntl37&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:27-29", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl24&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:20:1-6", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl25&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:30-33", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl26&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:5:34-36", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl27&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:36-43", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl29&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:37-41", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl2ndSunday||122ndSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:20:1-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl30&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:40-43", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl31&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:44-50", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl32&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:7:51-54", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl33&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:8:1-4", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl36&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:23-31", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl38&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:19:6-10", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl3&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:1-13", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl3rdSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:10:37-43", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl40&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:22:6-10", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl41&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:24:10-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl43&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:19-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl44&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:20-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl45&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:4-9", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl46&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:7-12", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl47&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:15:13-18", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl48&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:1:15-26", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl4thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:14:8-23", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl5&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:13:34-42", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl5thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:9:1-20", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl6thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:20:1-16", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl7thSunday||Pntl8thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:2:1-21", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl8&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:1-4", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=Pntl9&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:4:5-7", 
    ],
    ],
    [
    [
    Prefix.praxis+"&D=GL9thSunday&C=Title", 
    ],
    [
    Prefix.readingRef+"ACT:2:22-28", 
    ],
    ],
    ];