ReadingsArrays.PropheciesDawnArrayFR = [
    [
        [Prefix.prophecies + "&D=JFAST1"],
        [Prefix.readingRef + "JON:1:1-End/2:1-1"],
    ],
    [
        [Prefix.prophecies + "&D=JFAST2"],
        [Prefix.readingRef + "JON:2:2-End"],
    ],
    [
        [Prefix.prophecies + "&D=JFAST3"],
        [Prefix.readingRef + "JON:3:1-End/4:1-End"],
    ],
    [
        [Prefix.prophecies + "&D=GL10"],
        [Prefix.readingRef + "EXO:3:6-14"],
        [Prefix.readingRef + "ISA:4:2-End/5:1-7"],
    ],
    [
        [Prefix.prophecies + "&D=GL11"],
        [Prefix.readingRef + "JOB:19:1-27"],
        [Prefix.readingRef + "ISA:5:7-16"],
    ],
    [
        [Prefix.prophecies + "&D=GL12"],
        [Prefix.readingRef + "EXO:2:11-20"],
        [Prefix.readingRef + "ISA:5:17-25"],
        [Prefix.readingRef + "MAL:1:6-End/2:1-End/3:1-6"],
    ],
    [
        [Prefix.prophecies + "&D=GL13"],
        [Prefix.readingRef + "DEU:5:15-22"],
        [Prefix.readingRef + "ISA:6:1-12"],
        [Prefix.readingRef + "JOS:2:1-End/3:1-End/4:1-End/5:1-End/6:1-27"],
    ],
    [
        [Prefix.prophecies + "&D=GL14"],
        [Prefix.readingRef + "DEU:8:1-End/9:1-4"],
        [Prefix.readingRef + "1SA:17:1-End/18:1-4"],
        [Prefix.readingRef + "ISA:7:1-14"],
        [Prefix.readingRef + "JOB:11:1-20"],
    ],
    [
        [Prefix.prophecies + "&D=GL17"],
        [Prefix.readingRef + "PRO:1:20-33"],
        [Prefix.readingRef + "ISA:8:13-End/9:1-7"],
    ],
    [
        [Prefix.prophecies + "&D=GL18"],
        [Prefix.readingRef + "PRO:2:1-15"],
        [Prefix.readingRef + "ISA:10:12-20"],
        [Prefix.readingRef + "JOS:7:1-26"],
    ],
    [
        [Prefix.prophecies + "&D=GL19"],
        [Prefix.readingRef + "EXO:4:19-End/5:1-End/6:1-13"],
        [Prefix.readingRef + "JOL:2:21-26"],
        [Prefix.readingRef + "ISA:9:9-End/10:1-4"],
        [Prefix.readingRef + "JOB:12:1-End/13:1-End/14:1-22"],
    ],
    [
        [Prefix.prophecies + "&D=GL20"],
        [Prefix.readingRef + "GEN:18:17-End/19:1-29"],
        [Prefix.readingRef + "PRO:2:16-End/3:1-4"],
        [Prefix.readingRef + "ISA:11:10-End/11:1-End/12:1-2"],
    ],
    [
        [Prefix.prophecies + "&D=GL21"],
        [Prefix.readingRef + "DEU:9:7-End/10:1-11"],
        [Prefix.readingRef + "1SA:23:26-End/24:1-22"],
        [Prefix.readingRef + "JOB:15:1-35"],
        [Prefix.readingRef + "ISA:13:2-13"],
        [Prefix.readingRef + "SIR:2:1-End/3:1-4"],
    ],
    [
        [Prefix.prophecies + "&D=GL24"],
        [Prefix.readingRef + "GEN:27:1-41"],
        [Prefix.readingRef + "ISA:14:24-32"],
        [Prefix.readingRef + "JOB:16:1-End/17:1-End"],
    ],
    [
        [Prefix.prophecies + "&D=GL25"],
        [Prefix.readingRef + "GEN:28:10-22"],
        [Prefix.readingRef + "ISA:25:1-End/26:1-8"],
        [Prefix.readingRef + "JOB:18:1-21"],
    ],
    [
        [Prefix.prophecies + "&D=GL26"],
        [Prefix.readingRef + "EXO:7:14-End/8:1-18"],
        [Prefix.readingRef + "JOL:2:28-32"],
        [Prefix.readingRef + "JOB:1:1-22"],
        [Prefix.readingRef + "ISA:26:21-End/27:1-9"],
    ],
    [
        [Prefix.prophecies + "&D=GL27"],
        [Prefix.readingRef + "GEN:32:1-30"],
        [Prefix.readingRef + "ISA:28:14-22"],
        [Prefix.readingRef + "JOB:20:1-29"],
        [Prefix.readingRef + "DAN:6:1-27"],
    ],
    [
        [Prefix.prophecies + "&D=GL28"],
        [Prefix.readingRef + "DEU:10:12-End/11:1-28"],
        [Prefix.readingRef + "ISA:29:13-23"],
        [Prefix.readingRef + "JOB:21:1-34"],
        [Prefix.readingRef + "DAG:14:2-42"],
    ],
    [
        [Prefix.prophecies + "&D=GL31"],
        [Prefix.readingRef + "PRO:3:5-18"],
        [Prefix.readingRef + "ISA:37:33-End/38:1-6"],
        [Prefix.readingRef + "JOB:22:1-30"],
    ],
    [
        [Prefix.prophecies + "&D=GL32"],
        [Prefix.readingRef + "NUM:10:35-End/11:1-34"],
        [Prefix.readingRef + "PRO:3:19-End/4:1-9"],
        [Prefix.readingRef + "ISA:40:1-8"],
        [Prefix.readingRef + "JOB:25:1-6"],
        [Prefix.readingRef + "JOB:26:1-14"],
    ],
    [
        [Prefix.prophecies + "&D=GL33"],
        [Prefix.readingRef + "EXO:8:20-End/9:1-35"],
        [Prefix.readingRef + "ISA:41:4-14"],
        [Prefix.readingRef + "JOL:3:9-21"],
        [Prefix.readingRef + "JOB:28:12-28"],
        [Prefix.readingRef + "PRO:4:10-19"],
        [Prefix.readingRef + "1SA:1:1-End/2:1-21"],
    ],
    [
        [Prefix.prophecies + "&D=GL34"],
        [Prefix.readingRef + "ISA:42:5-16"],
        [Prefix.readingRef + "PRO:4:20-27"],
        [Prefix.readingRef + "JOB:29:2-20"],
    ],
    [
        [Prefix.prophecies + "&D=GL35"],
        [Prefix.readingRef + "DEU:11:29-End/12:1-27"],
        [Prefix.readingRef + "1KI:17:2-24"],
        [Prefix.readingRef + "PRO:5:1-12"],
        [Prefix.readingRef + "ISA:43:1-9"],
        [Prefix.readingRef + "JOB:30:9-End/31:1-End/32:1-5"],
    ],
    [
        [Prefix.prophecies + "&D=GL38"],
        [Prefix.readingRef + "PRO:8:1-11"],
        [Prefix.readingRef + "ISA:43:10-28"],
        [Prefix.readingRef + "JOB:32:6-16"],
    ],
    [
        [Prefix.prophecies + "&D=GL39"],
        [Prefix.readingRef + "PRO:8:12-21"],
        [Prefix.readingRef + "ISA:44:1-8"],
        [Prefix.readingRef + "JOB:32:17-End/33:1-33"],
    ],
    [
        [Prefix.prophecies + "&D=GL3"],
        [Prefix.readingRef + "EXO:2:23-End/3:1-5"],
        [Prefix.readingRef + "ISA:1:2-18"],
    ],
    [
        [Prefix.prophecies + "&D=GL40"],
        [Prefix.readingRef + "EXO:10:1-End/11:1-10"],
        [Prefix.readingRef + "ISA:44:21-28"],
        [Prefix.readingRef + "PRO:8:22-36"],
        [Prefix.readingRef + "JOB:34:1-37"],
    ],
    [
        [Prefix.prophecies + "&D=GL41"],
        [Prefix.readingRef + "2KI:4:8-41"],
        [Prefix.readingRef + "ISA:45:1-10"],
        [Prefix.readingRef + "PRO:9:1-11"],
        [Prefix.readingRef + "JOB:35:1-16"],
    ],
    [
        [Prefix.prophecies + "&D=GL42"],
        [Prefix.readingRef + "GEN:22:1-18"],
        [Prefix.readingRef + "ISA:45:11-17"],
        [Prefix.readingRef + "PRO:9:12-18"],
        [Prefix.readingRef + "JOB:36:1-33"],
        [Prefix.readingRef + "JOB:37:1-24"],
        [Prefix.readingRef + "TOB:1:1-End/2:1-End/3:1-6"],
        [Prefix.readingRef + "TOB:3:7-23"],
        [Prefix.readingRef + "TOB:3:24-End/4:1-End/5:1-End/6:1-9"],
        [Prefix.readingRef + "TOB:6:10-End/7:1-End/8:1-End/9:1-End"],
        [Prefix.readingRef + "TOB:10:1-End/11:1-End"],
        [Prefix.readingRef + "TOB:12:1-End/13:1-End/14:1-End"],
    ],
    [
        [Prefix.prophecies + "&D=GL45"],
        [Prefix.readingRef + "PRO:10:1-16"],
        [Prefix.readingRef + "ISA:48:17-End/49:1-4"],
        [Prefix.readingRef + "JOB:38:1-38"],
    ],
    [
        [Prefix.prophecies + "&D=GL46"],
        [Prefix.readingRef + "PRO:10:17-32"],
        [Prefix.readingRef + "ISA:49:6-10"],
        [Prefix.readingRef + "JOB:38:37-End/39:1-30"],
    ],
    [
        [Prefix.prophecies + "&D=GL47"],
        [Prefix.readingRef + "PRO:10:32-End/11:1-13"],
        [Prefix.readingRef + "ISA:58:1-11"],
        [Prefix.readingRef + "JOB:40:1-End/41:1-34"],
    ],
    [
        [Prefix.prophecies + "&D=GL48"],
        [Prefix.readingRef + "PRO:11:13-26"],
        [Prefix.readingRef + "ISA:65:8-16"],
        [Prefix.readingRef + "JOB:40:1-End/41:1-34"],
        [Prefix.readingRef + "2KI:6:8-End/7:1-20"],
    ],
    [
        [Prefix.prophecies + "&D=GL49"],
        [Prefix.readingRef + "GEN:49:33-End/50:1-1"],
        [Prefix.readingRef + "PRO:11:27-End/12:1-22"],
        [Prefix.readingRef + "ISA:66:10-24"],
        [Prefix.readingRef + "JOB:42:7-17"],
    ],
    [
        [Prefix.prophecies + "&D=GL4"],
        [Prefix.readingRef + "ISA:1:19-End/2:1-3"],
        [Prefix.readingRef + "ZEC:8:7-13"],
    ],
    [
        [Prefix.prophecies + "&D=GL50"],
        [Prefix.readingRef + "GEN:49:1-28"],
        [Prefix.readingRef + "ISA:40:9-31"],
        [Prefix.readingRef + "ZEP:3:14-20"],
        [Prefix.readingRef + "ZEC:9:9-15"],
    ],
    [
        [Prefix.prophecies + "&D=GL5"],
        [Prefix.readingRef + "ISA:2:3-11"],
        [Prefix.readingRef + "JOL:2:12-27"],
    ],
    [
        [Prefix.prophecies + "&D=GL6"],
        [Prefix.readingRef + "ISA:2:11-19"],
        [Prefix.readingRef + "ZEC:8:18-23"],
    ],
    [
        [Prefix.prophecies + "&D=GL7"],
        [Prefix.readingRef + "DEU:6:3-End/7:1-26"],
        [Prefix.readingRef + "ISA:3:1-14"],
    ],
];
